export default{
    PLATE:require("../assets/images/logo2.png"),
    DISCOVER:require("../assets/images/information.png"),
    DISCOVER1:require('../assets/images/head1.png'),
    DELIVER:require("../assets/images/orgar.png"),
    DELIVER1:require("../assets/images/head3.jpg"),
    FAVORITE:require("../assets/images/service.png"),
    FAVORITE1:require("../assets/images/head2.jpg"),
    FACEBOOK:require('../assets/images/facebook.png'),
    GOOGLE:require('../assets/images/google.png'),
    LOGO:require('../assets/images/mainlogo.png'),
    MASTERCARD:require('../assets/images/mastercard.png'),
    APPLEPAY:require('../assets/images/applepay.png'),
    APPLOGO:require('../assets/images/Applogo.png'),
    SUCCESS:require('../assets/images/success.png'),
    CLOSE:require('../assets/images/x.png'),
    RASENLOGO:require('../assets/images/whitelogo.png'),
    SHAVE:require('../assets/images/shave.png')
};
